#!/usr/bin/env bash

options=(
    "Themes"
    "Wallpapers"
    "Install package"
    "Remove package"
    "Update system"
)

selection=$(printf '%s\n' "${options[@]}" | rofi -dmenu -i -p "Menu")

case "$selection" in
"Themes")
    "$HOME"/Menu/scripts/style-switcher
    ;;
"Wallpapers")
    "$HOME"/Menu/scripts/wallpaper-switcher
    ;;
"Install package")
    "$HOME"/Menu/scripts/install

    ;;
"Remove package")
    "$HOME"/Menu/scripts/remove
    ;;
"Update system")
    "$HOME/.config/waybar/scripts/updates.sh"
    ;;
esac
